export const Constants = {
  COMMON_FAIL: "COMMON_FAIL",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_LOGGED_IN_FAIL: "USER_LOGGED_IN_FAIL",
  CHANGE_TO_USER: "CHANGE_TO_USER",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
  REGISTER_END: "REGISTER_END",

  GET_USER_CHATS_SUCCESS: "GET_USER_CHATS_SUCCESS",
  MAKE_CHATS_EMPTY: "MAKE_CHATS_EMPTY",
  COMMON_FAIL_USER: "COMMON_FAIL_USER",

  GET_USER_FRIENDS_SUCCESS: "GET_USER_FRIENDS_SUCCESS",
  GET_USER_FRIENDS_FAIL: "GET_USER_FRIENDS_FAIL",
};
